name: uta_picker
description: A simple tool to mark start/end times of songs in YouTube archives
version: 1.0.5
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.0.7
  file_picker: ^10.3.7
  path_provider: ^2.0.15
  sqflite_common_ffi: ^2.2.1
  shared_preferences: ^2.2.2
  intl: ^0.20.0
  url_launcher: ^6.2.2
  package_info_plus: ^9.0.0
  firebase_core: ^4.2.1
  firebase_analytics: ^12.0.4
  http: ^1.1.0
  scrollable_positioned_list: ^0.3.8

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/瀞ノグリッチ/
  fonts:
    - family: Torono Glitch Sans
      fonts:
        - asset: assets/fonts/瀞ノグリッチ/瀞ノグリッチ黒体H1.otf
          weight: 300
        - asset: assets/fonts/瀞ノグリッチ/瀞ノグリッチ黒体H2.otf
          weight: 400
        - asset: assets/fonts/瀞ノグリッチ/瀞ノグリッチ黒体H3.otf
          weight: 700
        - asset: assets/fonts/瀞ノグリッチ/瀞ノグリッチ黒体H4.otf
          weight: 900

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  mockito: ^5.6.1
  build_runner: ^2.10.4

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#ffffff"
    theme_color: "#0175C2"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon.png"
  linux:
    generate: true
    image_path: "assets/icon.png"
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon.png"